version: '3.7'
services:
  nginx:
    build: ./operations/docker/nginx
    ports:
      - 80:80
    volumes:
      - ./application:/var/www/application:cached
    links:
      - php
    networks:
      - nginx

  php:
    build:
      context: ./operations/docker/php
      args:
        - PUID=1000
        - LIVE=
    expose:
      - '9000'
      - '9001'
    volumes:
      - ./application:/var/www/application:cached
      - ./application/var/coverage:/opt/phpstorm-coverage:cached
    env_file:
      - docker-compose.env
    extra_hosts:
      - 'docker.host:127.0.0.1'
    networks:
      - application
      - nginx

networks:
  nginx: {}
  application:
    driver: bridge
