when@dev:
    twig:
        default_path: '%kernel.project_dir%/templates'
        strict_variables: true

when@test:
    twig:
        default_path: '%kernel.project_dir%/templates'
        strict_variables: true
