# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $databaseDateTimeFormat: 'Y-m-d H:i:s'
            $messageCommandBus: '@commands.bus'
            $messageEventBus: '@events.bus'
            $messageQueryBus: '@queries.bus'

    XIP\App\Infrastructure\Http\Web\Controller\:
        resource: '../src/App/Infrastructure/Http/Web/Controller/'
        tags: [ 'controller.service_arguments' ]

    XIP\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/'
            - '../src/*/Infrastructure/Http/*/Controller'
            - '../src/Kernel.php'

    _instanceof:
        XIP\Shared\Infrastructure\Http\Request\AbstractRequest:
            calls:
                - validate: []

    XIP\User\Domain\Repository\UserRepositoryInterface: '@XIP\User\Infrastructure\Repository\Doctrine\UserDoctrineRepository'
    XIP\User\Domain\Repository\RoleRepositoryInterface: '@XIP\User\Infrastructure\Repository\Doctrine\RoleDoctrineRepository'

    XIP\Shared\Domain\Bus\QueryBusInterface: '@XIP\Shared\Application\Bus\QueryBus'
    XIP\Shared\Domain\Bus\CommandBusInterface: '@XIP\Shared\Application\Bus\CommandBus'
    XIP\Shared\Domain\Bus\EventBusInterface: '@XIP\Shared\Application\Bus\EventBus'

    XIP\Shared\Domain\Http\Response\ResponseFactoryInterface: '@XIP\Shared\Infrastructure\Http\Response\ResponseFactory'

    XIP\App\Application\EventListeners\ConstraintViolationExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
