name: Run code checks.

on:
  push:
    branches: ['main']

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: 
          - 'unit'
          - 'check-style'
          # - 'phpstan'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare everything
        run: make prepare
      - name: Run reset of the app
        run: make reset

      - name: Start the containers
        run: make start
      
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  build:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build PHP base container
        run: docker build -t php -f application/Dockerfile application
      - name: Build PHP deployment container
        run: docker build -t deploy -f application/deploy.Dockerfile application
      
      - name: Tag PHP deployment container with commit hash
        run: docker tag deploy ghcr.io/xip-online-applications/coding-standards-poc:${{ github.sha }}
      - name: Tag PHP deployment container with latest
        run: docker tag deploy ghcr.io/xip-online-applications/coding-standards-poc:latest
      - name: Push PHP deployment container
        run: docker push -a ghcr.io/xip-online-applications/coding-standards-poc
