name: Run code checks.

on:
  push:
    branches: ['main']

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare everything
        run: make prepare
      - name: Run reset of the app
        run: make reset

      - name: Start the containers
        run: make start
      
      - name: Run the unit tests
        run: make unit
      - name: Run code analysis
        run: make qa
