name: Run code checks.

on:
  push:
    branches: ['main']

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['unit', 'qa']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare everything
        run: make prepare
      - name: Run reset of the app
        run: make reset

      - name: Start the containers
        run: make start
      
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
